namespace: misskey

resources:
  - ../../base

configMapGenerator:
  - name: misskey-web-config
    files:
      - default.yml=cfg/web.yml
  - name: media-proxy-configmap
    files:
      - config.json=cfg/config.json

patches:
  - path: patches/web.yaml
  - path: patches/media-proxy.yaml
