apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: misskey
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: web
          image: misskey/misskey:2023.11.1
