apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: misskey
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          image: misskey/misskey:2024.2.0
      hostAliases:
        - ip: "10.0.1.4" # which is the local IP of the physical machine that runs Ingress Controller
          hostnames:
            - "key.aoki.app"
