apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: misskey
spec:
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        storageClassName: ""
        resources:
          requests:
            storage: 256Mi
