apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: misskey
spec:
  replicas: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-files-pvc
  namespace: misskey
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
