url: https://key.aoki.app
port: 3000

#   ┌──────────────────────────┐
#───┘ PostgreSQL configuration └────────────────────────────────

db:
  host: pg-pooler-rw.pg-cluster.svc.cluster.local
  port: 5432
  db: misskey

  user: misskey-backend-user
  pass: misskey-backend-user # replaced by secret

  disableCache: true

# https://github.com/misskey-dev/misskey/issues/13921#issuecomment-2344350325
dbReplications: false

dbSlaves:
  - host: pg-pooler-ro.pg-cluster.svc.cluster.local
    port: 5432
    db: misskey
    user: misskey-backend-user
    pass: misskey-backend-user

redis:
  host: redis-service.misskey.svc.cluster.local
  port: 6379

id: "aid"

clusterLimit: 1

fullTextSearch:
  provider: sqlLike

# Job concurrency per worker
# deliverJobConcurrency: 128
# inboxJobConcurrency: 16

# Job rate limiter
# deliverJobPerSec: 128
# inboxJobPerSec: 16

# Job attempts
# deliverJobMaxAttempts: 12
# inboxJobMaxAttempts: 8

# IP address family used for outgoing request (ipv4, ipv6 or dual)
#outgoingAddressFamily: ipv4

# Proxy for HTTP/HTTPS
#proxy: http://127.0.0.1:3128

proxyBypassHosts:
  - www.recaptcha.net
  - hcaptcha.com
  - challenges.cloudflare.com

# Proxy for SMTP/SMTPS
#proxySmtp: http://127.0.0.1:3128   # use HTTP/1.1 CONNECT
#proxySmtp: socks4://127.0.0.1:1080 # use SOCKS4
#proxySmtp: socks5://127.0.0.1:1080 # use SOCKS5

# Media Proxy
mediaProxy: https://proxy.key.aoki.app/

# Proxy remote files (default: false)
#proxyRemoteFiles: true

# Sign to ActivityPub GET request (default: true)
signToActivityPubGet: true

allowedPrivateNetworks: ["127.0.0.1/32", "10.0.1.0/24"]
# Upload or download file size limits (bytes)
#maxFileSize: 262144000
