apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-proxy
  namespace: misskey
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-proxy
  template:
    metadata:
      labels:
        app: media-proxy
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: media-proxy
          image: ghcr.io/yojo-art/media-proxy-rs:main
          ports:
            - containerPort: 12766
          volumeMounts:
            - name: media-proxy-config
              mountPath: /media-proxy-rs/config.json
              subPath: config.json
      volumes:
        - name: media-proxy-config
          configMap:
            name: media-proxy-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: media-proxy-service
  namespace: misskey
spec:
  selector:
    app: media-proxy
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 12766
