apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: misskey

resources:
  - ../../base

configMapGenerator:
  - name: misskey-web-config
    files:
      - default.yml=cfg/web.yml

patches:
  - path: applications/psql.yaml
  - path: applications/redis.yaml
