apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-proxy-deployment
  namespace: misskey
spec:
  template:
    metadata:
      labels:
        app: media-proxy
    spec:
      hostAliases:
        - ip: "10.0.1.4"
          hostnames:
            - "key.aoki.app"
