apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: misskey
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web
          image: misskey/misskey:2024.3.1
      hostAliases:
        - ip: "10.0.1.4" # ad hoc fix: it's the one of the physical nodes where the Ingress Controller is placed
          hostnames:
            - "key.aoki.app"
