apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: misskey
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: default
      hostAliases:
        - ip: "10.0.1.4" # ad hoc fix: it's the one of the physical nodes where the Ingress Controller is placed
          hostnames:
            - "key.aoki.app"
